@identityUrl = https://localhost:5001/v1

# @name login
POST {{identityUrl}}/accounts/login HTTP/1.1
Content-Type: application/x-www-form-urlencoded
X-Trace-Id: identity1

userName=administrator
&password=!123ABCabc

###

@cookie = {{login.response.headers.Set-Cookie}}
@userName = officer1

# @name register
POST {{identityUrl}}/accounts HTTP/1.1
Content-Type: application/x-www-form-urlencoded
Cookie: {{cookie}}
X-Trace-Id: identity2

userName={{userName}}
&email=officer1@banking.com
&role=loan.officer

###

# @name getactivationlink
GET {{identityUrl}}/activationlinks/{{userName}} HTTP/1.1
Cookie: {{cookie}}
X-Trace-Id: identity3

###

@activationlinkId = {{getactivationlink.response.body.activationLinkId}}

# @name useactivationlinks
PATCH {{identityUrl}}/activationlinks/{{activationlinkId}} HTTP/1.1
X-Trace-Id: identiy4

###

@userCookie = {{useactivationlinks.response.headers.Set-Cookie}}
@changePasswordLocation = {{useactivationlinks.response.headers.Location}}
@password = !abc123ABC

# @name changepassword
PATCH {{changePasswordLocation}} HTTP/1.1
Content-Type: application/x-www-form-urlencoded
Cookie: {{userCookie}}
X-Trace-Id: identity5

password={{password}}
&confirmPassword={{password}}

###

@userLoginLocation = {{changepassword.response.headers.Location}}

# @name userlogin
POST {{userLoginLocation}} HTTP/1.1
Content-Type: application/x-www-form-urlencoded
X-Trace-Id: identity6

userName={{userName}}
&password={{password}}